<?php
$urlJs     = Mage::getUrl ( 'skin' ) . 'frontend/hgp/default/js/';
$urlMedia  = Mage::getUrl ( 'media' ) . 'googlemap/';
?>

<script type="text/javascript">
jQuery(function() {
	jQuery("map > area").tooltip({
	delay: 0,
	extraClass: "map > area",
	left: -200,
	top: 20,
	track: true});

});
</script>
<div id="map_interactive">
	<h3 class="hgp_h2"><?php echo $this->__('Search on the map'); ?></h3>
	<script type="text/javascript">
		//<![CDATA[
		document.write('<img src="<?php echo $urlMedia?>map.gif" alt="Map of Paris" id="mapParis" name="map" border="0" width="265" height="216" usemap="#Landkarte" />');
		//]]>
	</script>	
	<map name="Landkarte" id="map">
		
			<area shape="poly" coords="187,99,159,48,157,25,148,9,147,0,186,2,207,2,222,2,229,6,233,24,237,40,245,52,253,59,259,72,189,99" title="<?php echo $this->__('Canal Saint-Martin, Belleville, La Villette')?>" alt="<?php echo $this->__('Canal Saint-Martin, Belleville, La Villette')?>" onmouseover="map.src='<?php echo $urlMedia?>map1.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=1';?>'; return false;" />
			<area shape="poly" coords="146,66,132,66,107,67,85,39,81,24,102,7,116,2,129,2,147,0,149,10,154,22,157,26,158,47,164,60,146,66" title="<?php echo $this->__('Montmartre, Pigalle, Trinite')?>" alt="<?php echo $this->__('Montmartre, Pigalle, Trinite')?>" onmouseover="map.src='<?php echo $urlMedia?>map2.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=2';?>'; return false;" />
			<area shape="poly" coords="107,67,69,72,55,99,42,78,33,77,44,56,58,38,74,28,81,25,86,40,106,67" title="<?php echo $this->__('Porte Maillot, Monceau , Wagram, Champerret')?>" alt="<?php echo $this->__('Porte Maillot, Monceau , Wagram, Champerret')?>" onmouseover="map.src='<?php echo $urlMedia?>map3.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=3';?>'; return false;" />
			<area shape="poly" coords="14,172,3,166,3,143,9,121,15,106,25,92,34,76,42,78,56,99,54,116,34,141,14,171" title="<?php echo $this->__('Passy, Auteuil, Bois de Boulogne')?>" alt="<?php echo $this->__('Passy, Auteuil, Bois de Boulogne')?>" onmouseover="map.src='<?php echo $urlMedia?>map4.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=4';?>'; return false;" />
			<area shape="poly" coords="39,144,21,172,34,171,42,179,77,195,79,183,90,162,98,153,94,146,79,139,61,160,39,144" title="<?php echo $this->__('Porte de Versailles, Lecourbe, Andre Citroen')?>" alt="<?php echo $this->__('Porte de Versailles, Lecourbe, Andre Citroen')?>" onmouseover="map.src='<?php echo $urlMedia?>map5.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=5';?>'; return false;" />
			<area shape="poly" coords="98,153,107,167,114,165,130,173,135,197,131,214,109,208,76,195,82,175" title="<?php echo $this->__('Denfert Rochereau, Alesia, Cite universitaire')?>" alt="<?php echo $this->__('Denfert Rochereau, Alesia, Cite universitaire')?>" onmouseover="map.src='<?php echo $urlMedia?>map6.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=6';?>'; return false;" />
			<area shape="poly" coords="130,173,150,172,177,160,182,149,195,137,225,158,242,166,255,174,241,187,216,198,191,213,162,214,131,215,135,197,130,174" title="<?php echo $this->__('Bercy, Bois de Vincennes, BnF, Place d’Italie')?>" alt="<?php echo $this->__('Bercy, Bois de Vincennes, BnF, Place d’Italie')?>" onmouseover="map.src='<?php echo $urlMedia?>map7.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=7';?>'; return false;" />
			<area shape="poly" coords="187,100,190,126,195,136,225,157,244,166,255,174,262,164,262,150,263,137,261,117,262,96,260,71,187,100" title="<?php echo $this->__('Republique, Bastille, Nation')?>" alt="<?php echo $this->__('Republique, Bastille, Nation')?>" onmouseover="map.src='<?php echo $urlMedia?>map8.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=8';?>'; return false;" />
			<area shape="poly" coords="187,147,197,138,191,127,188,103,182,90,165,82,161,96,150,99,146,109,164,120,176,129,176,135,186,147" title="<?php echo $this->__('Marais, Les Halles, Beaubourg')?>" alt="<?php echo $this->__('Marais, Les Halles, Beaubourg')?>" onmouseover="map.src='<?php echo $urlMedia?>map9.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=9';?>'; return false;" />
			<area shape="poly" coords="180,88,166,83,161,95,150,99,147,108,117,91,111,91,114,82,107,67,148,66,165,60,181,88" title="<?php echo $this->__('Opera, Grands Boulevards, Bourse')?>" alt="<?php echo $this->__('Opera, Grands Boulevards, Bourse')?>" onmouseover="map.src='<?php echo $urlMedia?>map10.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=10';?>'; return false;" />
			<area shape="poly" coords="112,91,114,80,107,68,69,72,56,99,56,103,74,93,80,96,98,96,107,96,124,105,137,110,146,111,147,108,126,97,113,90" title="<?php echo $this->__('Louvre, Champs-Elysees, Etoile')?>" alt="<?php echo $this->__('Louvre, Champs-Elysees, Etoile')?>" onmouseover="map.src='<?php echo $urlMedia?>map11.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=11';?>'; return false;" />
			<area shape="poly" coords="61,160,39,144,35,140,53,116,56,104,74,93,80,96,98,96,99,102,101,106,101,125,95,126,95,146,80,139,61,159" title="<?php echo $this->__('Tour Eiffel, Trocadero, Invalides')?>" alt="<?php echo $this->__('Tour Eiffel, Trocadero, Invalides')?>"  onmouseover="map.src='<?php echo $urlMedia?>map12.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=12';?>'; return false;" />
			<area shape="poly" coords="94,147,96,127,101,125,101,105,98,100,98,96,107,97,134,109,142,111,148,123,138,154,139,163,132,172,115,165,107,167,95,147" title="<?php echo $this->__('Saint-Germain-des-Pres, Musee d’Orsay, Montparnasse')?>" alt="<?php echo $this->__('Saint-Germain-des-Pres, Musee d’Orsay, Montparnasse')?>"  onmouseover="map.src='<?php echo $urlMedia?>map13.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=13';?>'; return false;" />
			<area shape="poly" coords="130,172,138,162,138,154,148,124,142,111,148,111,165,120,175,129,176,134,185,146,180,154,178,159,169,164,152,172,130,172" title="<?php echo $this->__('Notre-Dame, Quartier Latin, ile Saint Louis')?>" alt="<?php echo $this->__('Notre-Dame, Quartier Latin, ile Saint Louis')?>" onmouseover="map.src='<?php echo $urlMedia?>map14.gif';" onmouseout="map.src='<?php echo $urlMedia?>map.gif';" onclick="javascript:document.location.href='<?php echo $this->getBaseUrl() . 'map.html?quartier=14';?>'; return false;" />
		
		
	</map>
</div>
