  <!-- start middle -->
        <div class="middle-container">
            <div class="middle col-1-layout">
                <?php //echo $this->getChildHtml('breadcrumbs') ?>
            <!-- start center -->
                <div id="main" class="col-main">
                <!-- start content -->
                	<?php echo $this->getChildHtml('global_messages') ?> 
                	<a class="link_top_static" href="<?php echo ($this->getUrl(''));?>" title="<?php echo $this->__('Back to home'); ?>">&gt;&nbsp;<?php echo $this->__('Back to home'); ?></a> 
                	<div class="top_gris_centre">&nbsp;</div> 
                	<div class="content_gris_centre">   
                		<div class="top_blanc_centre">&nbsp;</div>   
                		<div class="content_blanc_centre link-partner"> 
                			<div id="contenu_static"> 
								
								<h1><?php echo $this->__('Liens Partenaires'); ?></h1>
								<div id="container-intro">
									<h2><?php echo $this->__('Les adresses authentiques, insolites et intimes d’Hotels Grand Paris'); ?></h2>
									<p class="sous-titre"><?php echo $this->__('Le portail Hotels Grand Paris vous propose une selection'); ?></p>
								</div>
								<ul class="left-column">
									<li><h3><?php echo $this->__('Hôtels à Paris par quartier'); ?></h3></li>
									<li></li>
								</ul>
								
								
								
								
								<ul class="right-column">
									<li><h3><?php echo $this->__('Hôtels par catégories'); ?></h3></li>
								</ul>
                    		</div>
                    		
                    		<div class="clear"></div>
                    	</div>
                    	<div class="bottom_blanc_centre">&nbsp;</div>
                    	<div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                    <div class="bottom_gris_centre">&nbsp;</div>
                <!-- end content -->

                </div>
            <!-- end center -->

            </div>
        </div>
        <!-- end middle -->