  <!-- start middle -->
        <div class="middle-container">
            <div class="middle col-1-layout">
                <?php //echo $this->getChildHtml('breadcrumbs') ?>
            <!-- start center -->
                <div id="main" class="col-main">
                <!-- start content -->
                	<?php echo $this->getChildHtml('global_messages') ?> 
                	<a class="link_top_static" href="<?php echo ($this->getUrl(''));?>" title="<?php echo $this->__('Back to home'); ?>">&gt;&nbsp;<?php echo $this->__('Back to home'); ?></a> 
                	<div class="top_gris_centre">&nbsp;</div> 
                	<div class="content_gris_centre">   
                		<div class="top_blanc_centre">&nbsp;</div>   
                		<div class="content_blanc_centre sitemap"> 
                			<div id="contenu_static"> 
								
									<h1><?php echo $this->__('sitemap'); ?></h1>
									<div id="container-intro">
										<h2><?php echo $this->__('Hotels Grand Paris – Des Hôtels authentiques, insolites et intimes à Paris.'); ?></h2>
										<p><?php echo $this->__('identifier hotels'); ?></p>
										
										<p class="sous-titre"><?php echo $this->__('Pour un premier aperçu, visitez notre page'); ?></p>
										
										<p ><a class="quartier" href="<?php echo $this->getUrl('');?>quartiers-paris-arrondissement.html"><?php echo $this->__('Hôtels à Paris – Quel quartier choisir'); ?></a></p>
								</div>
								<ul class="left-column">
									<li><h3><?php echo $this->__('Hôtels à Paris par quartier'); ?></h3></li>
									<li>
										<ul>
											<li><h4><a title='<?php echo $this->__('Hotels Paris Opera, Hotels Paris Madeleine & Hotels Paris St Lazare')?>' href='<?php echo $this->getUrl('');?>hotel-opera-paris.html'><?php echo $this->__('Hôtels Opéra, Madeleine et Saint Lazare')?></a></h4></li>
												<li><a title='<?php echo $this->__('Title Ouest Hotel')?>' href="<?php echo $this->getUrl('');?>ouest-hotel-paris.html"><?php echo $this->__('Ouest Hotel2'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Opera Opal')?>' href="<?php echo $this->getUrl('');?>hotel-opera-opal-paris.html"><?php echo $this->__('Hotel Opal'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Opera Diamond')?>' href="<?php echo $this->getUrl('');?>hotel-opera-diamond-paris.html"><?php echo $this->__('Hotel Opéra Diamond'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Opera Faubourg')?>' href="<?php echo $this->getUrl('');?>hotel-opera-faubourg-paris.html"><?php echo $this->__('Hotel Jules'); ?></a></li>
												
												
											<li><h4><a title='<?php echo $this->__('Hotels Paris Champs Elysees & Hotels Paris Arc de Triomphe')?>' href='<?php echo $this->getUrl('');?>hotel-champs-elysees-paris.html'><?php echo $this->__('Hôtels Champs-Elysées et Arc de Triomphe')?></a></h4></li>
												<li><a title='<?php echo $this->__('Title Mac Mahon')?>' href="<?php echo $this->getUrl('');?>hotel-mac-mahon-paris.html"><?php echo $this->__('Hotel Mac Mahon'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Elysee Secret')?>' href="<?php echo $this->getUrl('');?>hotel-elysee-secret-paris.html"><?php echo $this->__('Hotel Elysee Secret'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Beauchamps')?>' href="<?php echo $this->getUrl('');?>hotel-beauchamps-paris.html"><?php echo $this->__('Hotel Beauchamps'); ?></a></li>
												
											<li><h4><a title='<?php echo $this->__('Hotels Paris St Germain des Pres & Hotels Paris Montparnasse')?>' href='<?php echo $this->getUrl('');?>hotel-montparnasse-saint-germain.html'><?php echo $this->__('Hôtels Saint Germain des Prés et Montparnasse')?></a></h4></li>
												<li><a title='<?php echo $this->__('Title Bretagne')?>' href="<?php echo $this->getUrl('');?>hotel-bretagne-montparnasse.html"><?php echo $this->__('BEST WESTERN Bretagne Montparnasse'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Sevres')?>' href="<?php echo $this->getUrl('');?>hotel-sevres-montparnasse.html"><?php echo $this->__('Hotel Sevres Montparnasse'); ?></a></li>
												<li><a title='<?php echo $this->__('Title HiM')?>' href="<?php echo $this->getUrl('');?>holiday-inn-paris-gare-montparnasse.html"><?php echo $this->__('Holiday InnParis Gare Montparnasse'); ?></a></li>
												
											<li><h4><a title='<?php echo $this->__('Hotels Paris Louvre, Hotel Paris Marais & Hotel Paris Beaubourg')?>' href='<?php echo $this->getUrl('');?>hotel-louvre-paris.html'><?php echo $this->__('Hôtels Louvre & Marais')?></a></h4></li>
												<li><a title='<?php echo $this->__('Title Ducs')?>' href="<?php echo $this->getUrl('');?>hotel-ducs-de-bourgogne-paris.html"><?php echo $this->__('Hotel aux Ducs de Bourgogne2'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Louvre')?>' href="<?php echo $this->getUrl('');?>hotel-louvre-saint-honore.html"><?php echo $this->__('Hotel Louvre Saint Honore2'); ?></a></li>
												<li><a title='<?php echo $this->__('Title MGB')?>' href="<?php echo $this->getUrl('');?>hotel-marais-grands-boulevards.html"><?php echo $this->__('Hotel France Europe2'); ?></a></li>
												
											<li><h4><a title='<?php echo $this->__('Hotels Paris Gare de Lyon, Hotels Paris Nation, HotelsVincennes')?>' href='<?php echo $this->getUrl('');?>hotel-gare-lyon-paris.html'><?php echo $this->__('Hôtels Gare de Lyon, & Nation Paris')?></a></h4></li>
												<li><a title='<?php echo $this->__('Title 61PNH')?>' href="<?php echo $this->getUrl('');?>61-paris-nation-hotel.html"><?php echo $this->__('61 Paris Nation Hotel'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Saint Louis')?>' href="<?php echo $this->getUrl('');?>hotel-saint-louis-vincennes.html"><?php echo $this->__('Hotel Saint-Louis2'); ?></a></li>
																							
											<li><h4><a title='<?php echo $this->__('Hotels Paris Wagram & Hotels Paris Batignolles')?>' href='<?php echo $this->getUrl('');?>hotel-wagram-paris.html'><?php echo $this->__('Hôtels Wagram & Batignolles')?></a></h4></li>
												<li><a title='<?php echo $this->__('Title Batignolles')?>' href="<?php echo $this->getUrl('');?>opera-batignolles.html"><?php echo $this->__('Hotel Square des Batignolles2'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Neuville')?>' href="<?php echo $this->getUrl('');?>hotel-de-neuville-paris.html"><?php echo $this->__('Hotel de Neuville'); ?></a></li>
											
											<li><h4><a title='<?php echo $this->__('Hotels Gare du Nord & Gare de lest')?>' href='<?php echo $this->getUrl('');?>hotel-gare-du-nord.html'><?php echo $this->__('Hotels Gare du Nord & Gare de lest')?></a></h4></li>
												<li><a title='<?php echo $this->__('Title Mercure')?>' href="<?php echo $this->getUrl('');?>mercure-paris-terminus-nord.html"><?php echo $this->__('Mercure Paris Terminus Nord'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Faubourg 88')?>' href="<?php echo $this->getUrl('');?>best-western-premier-faubourg-88-paris.html"><?php echo $this->__('BEST WESTERN PREMIER Faubourg 88'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Hi Est')?>' href="<?php echo $this->getUrl('');?>holiday-inn-paris-gare-de-l-est.html"><?php echo $this->__('Holiday Inn Paris Gare de lest'); ?></a></li>
												<li><a title='<?php echo $this->__('Title Aulivia')?>' href="<?php echo $this->getUrl('');?>best-western-aulivia-opera.html"><?php echo $this->__('Aulivia Opéra2'); ?></a></li>

											
											<li><h4><?php echo $this->__('Et aussi'); ?></h4></li>
												<li><a title='<?php echo $this->__('Hotels Paris Arc de Triomphe')?>' href="<?php echo $this->getUrl('');?>hotel-arc-de-triomphe-paris.html"><?php echo $this->__('Hôtels Arc de Triomphe Paris'); ?></a></li>
												<li><a title='<?php echo $this->__('Hotel Paris Gare du Nord')?>' href="<?php echo $this->getUrl('');?>hotel-gare-du-nord.html"><?php echo $this->__('Hôtel Gare du Nord'); ?></a></li>
												<li><a title='<?php echo $this->__('Hotel Paris Gare de lEst')?>' href="<?php echo $this->getUrl('');?>hotel-gare-est.html"><?php echo $this->__('Hôtel Gare de lEst'); ?></a></li>
												<li><a title='<?php echo $this->__('Hotels Paris Gare Montparnasse')?>' href="<?php echo $this->getUrl('');?>hotel-gare-montparnasse.html"><?php echo $this->__('Hôtels Gare Montparnasse'); ?></a></li>
												<li><a title='<?php echo $this->__('Hotels Paris Gare Saint Lazare')?>' href="<?php echo $this->getUrl('');?>hotel-gare-saint-lazare-paris.html"><?php echo $this->__('Hôtels Gare Saint Lazare'); ?></a></li>
												<li><a title='<?php echo $this->__('Hotel Paris Nation')?>' href="<?php echo $this->getUrl('');?>hotel-nation-paris.html"><?php echo $this->__('Hôtel Nation Paris'); ?></a></li>
										</ul>
									</li>
								</ul>
								
								
								
								
								<ul class="right-column">
									<li><h3><?php echo $this->__('Hôtels par catégories'); ?></h3></li>
									<li>
										<ul>
											<li><a title='<?php echo $this->__('3 Star Hotel in Paris')?>' href="<?php echo $this->getUrl('');?>hotel-3-etoiles-paris.html"><?php echo $this->__('Hôtels 3 étoiles Paris'); ?></a></li>
											<li><a title='<?php echo $this->__('4 Star Hotel in Paris')?>' href="<?php echo $this->getUrl('');?>hotel-4-etoiles-paris.html"><?php echo $this->__('Hôtels 4 étoiles Paris'); ?></a></li>
											<li><a title='<?php echo $this->__('5 Star Hotel in Paris')?>' href="<?php echo $this->getUrl('');?>hotel-5-etoiles-paris.html"><?php echo $this->__('Hôtels 5 étoiles Paris'); ?></a></li>
											
											<li><h4><?php echo $this->__('Et aussi'); ?></h4></li>
											<li><a title='<?php echo $this->__('Hotels Paris Best Western')?>' href="<?php echo $this->getUrl('');?>best-western-paris.html"><?php echo $this->__('Sélection de Best Western'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotels Paris Best Western Premier')?>' href="<?php echo $this->getUrl('');?>best-western-premier-paris.html"><?php echo $this->__('Sélection de Best Western Premier'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotels Paris Best Western Plus')?>' href="<?php echo $this->getUrl('');?>best-western-plus-paris.html"><?php echo $this->__('Sélection de Best Western Plus'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotels Paris Maison Albar')?>' href="<?php echo $this->getUrl('');?>maison-albar-paris.html"><?php echo $this->__('Sélection Maison Albar Paris'); ?></a></li>
										</ul>
									</li>
									
									<li><h3><?php echo $this->__('Hôtels par arrondissement'); ?></h3></li>
									<li>
										<ul>
											<li><a title='<?php echo $this->__('Hotels in 1st arrondissement Paris')?>' href="<?php echo $this->getUrl('');?>hotels-paris-1er-arrondissement.html"><?php echo $this->__('Hôtels Paris 1er'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotel in 3rd arrondissement Paris')?>' href="<?php echo $this->getUrl('');?>hotel-paris-3eme-arrondissement.html"><?php echo $this->__('Hôtels Paris 3eme'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotels in 8th arrondissement Paris')?>' href="<?php echo $this->getUrl('');?>hotel-paris-8eme-arrondissement.html"><?php echo $this->__('Hôtels Paris 8eme'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotels in 9th arrondissement Paris')?>' href="<?php echo $this->getUrl('');?>hotel-paris-9eme-arrondissement.html"><?php echo $this->__('Hôtels Paris 9eme'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotels in 10th arrondissement Paris')?>' href="<?php echo $this->getUrl('');?>hotel-paris-10eme-arrondissement.html"><?php echo $this->__('Hôtels Paris 10eme'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotels in 12th arrondissement Paris')?>' href="<?php echo $this->getUrl('');?>hotel-paris-12eme-arrondissement.html"><?php echo $this->__('Hôtels Paris 12eme'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotels in 14th arrondissement Paris')?>' href="<?php echo $this->getUrl('');?>hotel-paris-14eme-arrondissement.html"><?php echo $this->__('Hôtels Paris 14eme'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotels in 15th arrondissement Paris')?>' href="<?php echo $this->getUrl('');?>hotel-paris-15eme-arrondissement.html"><?php echo $this->__('Hôtels Paris 15eme'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotels in 17th arrondissement Paris')?>' href="<?php echo $this->getUrl('');?>hotel-paris-17eme-arrondissement.html"><?php echo $this->__('Hôtels Paris 17eme'); ?></a></li>
											<li><a title='<?php echo $this->__('Hotel Vincennes')?>' href="<?php echo $this->getUrl('');?>hotel-vincennes.html"><?php echo $this->__('hotel'); ?> <?php echo $this->__('Vincennes'); ?></a></li>
										</ul>
									</li>
									
									<li><h3><?php echo $this->__('Hôtels par Style'); ?></h3></li>
									<li>
										<ul>
											<li><a title='<?php echo $this->__('Boutique hotels Paris')?>' href="<?php echo $this->getUrl('');?>boutique-hotel-paris.html"><?php echo $this->__('Boutique Hôtel Paris'); ?></a></li>
											<li><a title='<?php echo $this->__('Luxury Hotels Paris')?>' href="<?php echo $this->getUrl('');?>hotel-de-luxe-paris.html"><?php echo $this->__('Hôtels de Luxe Paris'); ?></a></li>
											<li><a title='<?php echo $this->__('Small Hotels Paris')?>' href="<?php echo $this->getUrl('');?>hotel-de-charme-paris.html"><?php echo $this->__('Hôtels de charme Paris'); ?></a></li>
											<li><a title='<?php echo $this->__('Romantic Hotels Paris')?>' href="<?php echo $this->getUrl('');?>hotel-romantique-paris.html"><?php echo $this->__('Hôtels romantique Paris'); ?></a></li>
											<li><a title='<?php echo $this->__('Great hotels Paris')?>' href="<?php echo $this->getUrl('');?>great-hotels-in-paris.html"><?php echo $this->__('Hôtels Sympa Paris'); ?></a></li>
											<li><a title='<?php echo $this->__('Budget Hotels Paris')?>' href="<?php echo $this->getUrl('');?>budget-hotels-in-paris.html"><?php echo $this->__('Hôtels pas cher Paris'); ?></a></li>
										</ul>
									</li>
									<li><h3><?php echo $this->__('Les pages principales du site'); ?></h3></li>
										<li>
											<ul>
												<li><a title='<?php echo $this->__('Hotels Grand Paris - Hotels in Paris City Centre')?>' href="<?php echo $this->getUrl('');?>"><?php echo $this->__('Home'); ?></a></li>
												<li><a title='<?php echo $this->__('Hotels Grand Paris - Hotels Paris')?>' href="<?php echo $this->getUrl('');?>hotel.html"><?php echo $this->__('Hotel'); ?> Paris</a></li>
												<li><a title='<?php echo $this->__('Hotels Grand Paris - Map of Paris')?>' href="<?php echo $this->getUrl('');?>map.html"><?php echo $this->__('Map of Paris'); ?></a></li>
												<li><a title='<?php echo $this->__('Hotels Grand Paris - About us')?>' href="<?php echo $this->getUrl('');?>about-us.html"><?php echo $this->__('About us'); ?></a></li>
												<li><a title='<?php echo $this->__('Hotels Grand Paris - Partnership')?>' href="<?php echo $this->getUrl('');?>partnership.html"><?php echo $this->__('Partenaireship'); ?></a></li>
												<li><a title='<?php echo $this->__('Hotels Grand Paris - Contact us')?>' href="<?php echo $this->getUrl('');?>contacts/"><?php echo $this->__('Contacts'); ?></a></li>
												<li><a title='<?php echo $this->__('Hotels Grand Paris - Terms & conditions')?>' href="<?php echo $this->getUrl('');?>terms.html"><?php echo $this->__('Conditions générales'); ?></a></li>
												
											</ul>
										</li>
								</ul>
                    		</div>
                    		<div class="clear"></div>
                    	</div>
                    	<div class="bottom_blanc_centre">&nbsp;</div>
                    	<div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                    <div class="bottom_gris_centre">&nbsp;</div>
                <!-- end content -->

                </div>
            <!-- end center -->

            </div>
        </div>
        <!-- end middle -->